language: android
sudo: required
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - android-23
  - android-21
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-android-21
env:
  global:
  - secure: RKNEdMlUMqxtrDg4hP12vypK7dHQjO+19mdUfQ+Iat+F1SJSKnPbJDF53/zMSscGum49WTpScOcpvOoTylN9+gOAyqC0orZPJz8b9ptyxxMdRhUC/ZZACYuf9o4X/aiTYdS4ArrCI5wHaFgGpx5u1cuKKHbKPBMSi5XDcnhBvUdbCcwomJ5r/mhnxFu2zTW/rkVdvsiFhmWk4WbkJYgCESIgcPPk6L66XwQ3gBiOcbtvTc6O2cCBP1uVzcG3nroDB2z4KSOFwfA3O9rFQ9HR7jgtgWEyFHuaSnXdUQ9bD12SEI9xK/ByhZBN4EcC+L+WI0AoY5CPWbNgYJomm4FG7Tv+qzkUkHV4GWCZjEAnKP2Ha0Mr32uOTgJ4D0bquXZb6N8mvmQTivsh78GiclPyN0gA/YQbcHhY5a4FfkL1YODjw3DnMQmbowzbrZa5wxXdn8enAS9/+L+eZM9VQW/JnwNGRsrP8qXMOOZTV7q8mNs7ZvzPkqOat7C0/ZiPcErOxFpKpMerWuSVUOlB3rFb7rHv7XNMdG7qGYDHUIOVlk8vnE6494ZgvmAu1gwnj5DBozd2R3zfAc0/Ms3VH4xOghwfdn6r+aSGaspiK7lsW6qzTCvEtmcc647CQfNxY01OKFlYriotslDuJyXOYCc81ZQvPujqMjzHOifW6ScRC3M=
  - secure: n4apmWOLIDqc8rEEseLyuHGjMYMggj7iipDtUxI+PdfjB3puQdWdPUwN4eoGGuYTU0RT9ITQ1e8bY50jXIla7/zR1jR5ITT1ydZ696icfvfNBRaG/24qG3olXgal4uB2vp39qE6OfQ4B2v0iA3F8EEXTpJSm2H5ZLOt1fJHNQQUQ7yd8itl16izMrDtGuZtbb865W9rDOTBoSWkg3rf1OIysqApZu5ayQCvAPHvncVTJ64QElXTKuWoV5Avq5MQuIru4+ooCGx5gLvILvW44+f2eI3wVoJjBE5FJYUCpFZR9GjarL9c9/pEzLhqpM5/1T/jmgWv49HOio9DemeGoK9Xeb35Uym+rNh/J43YrklzXTidPEA2l++rjHo4SReEUysWCaFY35GZfQWyARFAifXoX9QVfcfIaenJpXlipleuUJu/2+RSXSQsBbQw3mAmmS/oBv4L4g1JksG940S0Miy5kYgHpFnk0UGZ935rFxL9Gy1ZBdo6sBNIIxphhaa9KVN8ux9HjDJmlvUvun3OZvybQk828JrdioWtOVnL1WaUSHKtqW5ZOBLwUJuFdCGjXjTzuTNiK+S2lgg8eVYrxFWWBvdPKFC+22jf7vyrummzNwYDS0FdOzR7SjBEK4RKrkTbuLMC822MlECAg7C2tFitDntqJ1fX9nnrpOso85qQ=
  - secure: t18n8dMnfL5pxDUz/F98uxxV6QKLqBh9xU6TPnTLnVVIUAw6AiIvA4MF76G27S0lzUzHsVfMTrioHwk25PxRtCVmHThlwe5WqlUWdU1N+yd2sV2I1d0jME86eKWmRWfdQnGVQ+6+m2yMIAOz/n6xTPd5lPDOrHwHIoCC11ti+OntGGAdM+RYiPHsBNryKporavRDr55HEaMKlBUYO6bupNzpNOd0SxFujKPW5lrdcpHJuzDMmiwekdHE6SERpZqObJGotHZktrNHEpUib4hCZU8K20tg4PPgkM72+iuvBELUIQz2CACfcy5DwFJooeTND0OrmmtW3VCGV3EVUAj+olzSmoASm080kyErOkniv4weALImSr2E69Ta08MoZ6YVK2K6PuDDW78SmQfsows5MgDp1tVnfSVL3BuXNGk5k/nChUlXeE4B3xl8MFcP6z+vT41q7BJpceLChHmTBD6uGzAhFR098em3peeo3iX5AKhEgYFfblWWgfWll1kLp9+SW9+vzCo0E7GqCcThwyRMgP0JAQV8/vp3d7MW7hKvXxxg5JwxjlfZfoVCBkRKiC86b7NCcfI6GA43GZVgjKoYovBMVhpKZ5alzw3Lt3FwixOnSre+Auq7KHykL5+Xxz5BuZrJeJtet57c4acTgi7tM8hnKOz6puh8+ICegDsN8V8=
  - secure: K7VrwNa762tS80iqjXclIQqyTZ9Ljqhmmc9tECVtzct/Q2nZLeJiQUg+8ERUnTQSncA48RNfo+t17ON12z7TWA8AMzVAci/LXV90f7ozbHvN4549ikFF7DoY2JRc4+NAuN7ldFaGbqjBi8wya9n/BTPKOF4LneXndXnYBWWMEySiaKYSb65+REkEkUZaXG1UPkUWZ+1q7GjyxJaV1SgT63hq1heT861jFWo0Kp1/vSwKbAEHPPUG8m1pBK68eebf7fUY2GEH6t2pYK+hWj4m73sI9j5ik8CG793MZoMHgltsvhlOUq5ZqVXo/z9QKcYbWhJP1GRiFZwxhup2KYoYo1p5QmWEr0SxSvxjrp76SP86iCs293jETazejuGbti6GSySGM0kXUqjOSc/WzHTrLclpUvz9VMQBMFQkoPnEuB++Do+MuEcAbzXpDQm9btOf9S641BfXqf4PXRFNr0k8DYURcVRnEitx/Y1nGVBKk/Ynu2DPY2T1woyAw4sFMykcwd8egT4awarJBTbag3jrJT1BTLWZxmmcBOlu60TzODMmkYB2/HrZTchZXRvwFP8cqIMokMgSJk083GceicaZBh8cYdPPfYsmrpyMf3SHqUxvBqdZEnYqWgpSdSqWyMNVDFYg9844a6dhs1+4RDXcZja0wTAmKr1J9+Sas57wHlc=
before_install:
- openssl aes-256-cbc -k "$fabric_encryption_key" -in app/fabric.properties.enc -out
  app/fabric.properties -d
- openssl aes-256-cbc -k "$keystore_encryption_key" -in app/releaseKeystore.jks.enc -out app/releaseKeystore.jks -d
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
- ./gradlew dependencies || true
script: ./gradlew assembleRelease
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_script:
- rm app/fabric.properties
- rm app/releaseKeystore.jks
