fastlane_version "2.19.3"

default_platform :android

platform :android do

  desc "Submit a new Alpha Build to Android Alpha and Crashlytics Beta"
  lane :alpha do
    gradle(task: "assembleRelease")
    supply(track: "alpha")
  end

  desc "Submit a new Beta Build to Android Beta"
  lane :promote_alpha do
    supply(track: "alpha", track_promote_to: "beta")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end
end
