fastlane_version "2.19.3"

default_platform :android

platform :android do

  desc "Create a Release APK"
  lane :release do
    gradle(task: "assembleRelease")
  end

  desc "Submit a new Alpha Build to Android Alpha and Crashlytics Beta"
  lane :alpha do
    supply(track: "alpha", apk: "app/build/outputs/apk/app-release.apk")
    crashlytics(
      api_token: "4b7b97384889bb0454d04c0092e637476844024e",
      apk_path: "app/build/outputs/apk/app-release.apk",
    )
  end

  desc "Submit a new Beta Build to Android Beta"
  lane :promote_alpha do
    supply(track: "alpha", track_promote_to: "beta")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    supply
  end
end
